version: "3"
services:
  locast2tuner:
    image: ghcr.io/wouterdebie/locast2tuner:latest
    container_name: locast2tuner
    environment:
      - l2t_username=username
      - l2t_password=password
#      - l2t_override_zipcodes=#####,##### (optional)
#      - l2t_multiplex=true (optional)
#      - l2t_remap=true (optional)
    ports:
      - 6077:6077
    restart: unless-stopped
